"""Active discovery — the agent manufactures evidence instead of waiting for it.

Every other tool in this space is a filing cabinet: it can only organize what
the school chose to send. Minutes instead exercises the parent's statutory
records rights on a fixed cadence, so the school faces a dated deadline it must
either meet or miss. Both outcomes are useful. If it produces its service logs,
the ledger gains ``SCHOOL_CONFIRMED`` minutes — the single most decisive
evidence in a shortfall case, and the one record the district controls. If it
produces nothing, the missed deadline is itself a dated fact
(``Provenance.DOCUMENTED_SILENCE``) that a parent could never have generated by
observation alone.

THE HONESTY RULE THIS MODULE EXISTS TO ENFORCE: silence is evidence about the
RECORDS, never about the child's services. An unanswered request establishes
that the school did not produce documentation for a period when it was legally
required to. It does not establish that a session was missed.

That rule binds every consumer of what this module returns, not only this file.
A ``ServiceEvent`` carrying ``Provenance.DOCUMENTED_SILENCE`` has
``delivered=False`` because no delivery is documented, NOT because a
non-delivery is documented. Any citation, footnote or letter sentence derived
from such an event must describe the absence of a RECORD ("no service record
was produced for this period") and must never describe the session as
"recorded as not delivered" — that is a claim about the child's services that
silence cannot support. Consumers that render evidence by branching on
``delivered`` alone will state it anyway, so they must branch on
``provenance`` first. See :func:`silence_events`.

This module decides WHEN to ask and tracks the STATE of every ask. It makes no
LLM calls and writes no prose; the letter that carries a request is assembled
elsewhere from these dates.
"""

from __future__ import annotations

import re
from datetime import date, timedelta

from .models import (
    IEPLedger,
    Provenance,
    RecordsRequest,
    RequestState,
    ServiceEvent,
)

RESPONSE_WINDOW_DAYS = 45
"""The outer statutory ceiling for producing education records.

34 CFR 300.613(a): the agency "must comply with a request without unnecessary
delay and before any meeting regarding an IEP, or any hearing ... or resolution
session ..., and in no case more than 45 days after the request has been made."
34 CFR 99.10(b) sets the same 45-day ceiling under FERPA, running from receipt.

Two things this constant is NOT. It is not a safe harbour: 300.613(a) stacks
three deadlines and the earliest governs, so naming an upcoming IEP meeting
turns 45 days into that meeting date (see ``mark_sent``). And it is not
necessarily the operative number: several states impose shorter special
education records deadlines, so 45 days is the worst case a per-state layer
would tighten.

Days are calendar days — 34 CFR 300.11(a) defines "day" as a calendar day
unless otherwise indicated, so school breaks and summer do not toll the clock.
"""

# A request that is drafted or in flight already covers its window; issuing a
# second one would double-count the same period. An UNANSWERED_OVERDUE request
# is deliberately NOT in this set: the school has already blown its deadline,
# that period's silence is recorded, and the cadence must keep running rather
# than stall behind a school that simply never answers.
_OPEN_STATES = frozenset({RequestState.DRAFT, RequestState.SENT})


def due_requests(
    ledger: IEPLedger,
    existing: list[RecordsRequest],
    today: date,
    cadence_days: int = 30,
) -> list[RecordsRequest]:
    """Return DRAFT requests that should be sent today, or an empty list.

    The coverage window runs from the day after the most recent request's
    ``covers_end`` (or the earliest obligation start date, for the first
    request) through ``today``, so consecutive requests tile the school year
    without gaps or overlaps. A request comes due once that uncovered window is
    at least ``cadence_days`` days long, counted inclusively.

    Nothing is returned while a DRAFT or SENT request is open, so the agent
    never asks twice for the same period or crowds a school that is still
    inside its statutory response window.

    ``services`` lists only obligations whose own date range overlaps the
    window; a service that ended in December is not asked about in March.

    Raises:
        ValueError: if ``cadence_days`` is less than 1. A zero or negative
            cadence is not "ask immediately", it is an unbounded request
            generator — one new request against the district on every run,
            which is both legally counterproductive and the exact pattern the
            cadence exists to prevent.
    """
    if cadence_days < 1:
        raise ValueError(
            f"cadence_days must be at least 1, got {cadence_days}; a non-positive "
            "cadence would issue a fresh records request on every run"
        )

    if any(r.state in _OPEN_STATES for r in existing):
        return []

    covered_through = max((r.covers_end for r in existing), default=None)
    window_start = _window_start(ledger, covered_through)
    if window_start is None or window_start > today:
        return []

    if (today - window_start).days + 1 < cadence_days:
        return []

    services = _services_in_window(ledger, window_start, today)
    if not services:
        return []

    return [
        RecordsRequest(
            request_id=_next_request_id(existing),
            covers_start=window_start,
            covers_end=today,
            services=services,
            state=RequestState.DRAFT,
        )
    ]


def mark_sent(
    request: RecordsRequest,
    sent_on: date,
    *,
    before_meeting_on: date | None = None,
) -> RecordsRequest:
    """Record that a request went out, and compute the date it becomes overdue.

    ``response_due`` is ``sent_on`` plus ``RESPONSE_WINDOW_DAYS`` calendar days
    (34 CFR 300.613(a); 34 CFR 99.10(b); calendar days per 34 CFR 300.11(a)).

    Pass ``before_meeting_on`` — the date of an UPCOMING IEP meeting, hearing,
    or resolution session — to use the earlier of the two dates instead. Under
    34 CFR 300.613(a) production is owed "before any meeting regarding an IEP",
    so naming a meeting 12 days out converts the 45-day ceiling into a 12-day
    deadline. This is the single highest-leverage date in the whole mechanism,
    which is exactly why it is validated rather than trusted: a meeting date
    that does not postdate the send is rejected outright. A stale meeting
    record, a typo, or a caller passing the LAST IEP meeting instead of the
    next one would otherwise produce a ``response_due`` earlier than
    ``sent_on`` — a fabricated breach of a deadline that expired before the
    request existed. Nothing downstream can detect that, so it must never be
    constructed here.

    The clock runs from receipt, so the caller should pass the date a
    delivery-confirmed channel proves the school received it, not the date it
    was composed.

    Raises:
        ValueError: if ``request`` is not a DRAFT, or if ``before_meeting_on``
            is on or before ``sent_on``.
    """
    if request.state is not RequestState.DRAFT:
        raise ValueError(
            f"request {request.request_id} is {request.state.value}, not draft; "
            "re-sending would reset a response clock that has already started"
        )

    if before_meeting_on is not None and before_meeting_on <= sent_on:
        raise ValueError(
            f"before_meeting_on {before_meeting_on.isoformat()} is not after "
            f"sent_on {sent_on.isoformat()}; a meeting that has already been held "
            "cannot shorten a production clock that starts today, and dating the "
            "deadline into the past would allege a breach that predates the request"
        )

    response_due = sent_on + timedelta(days=RESPONSE_WINDOW_DAYS)
    if before_meeting_on is not None and before_meeting_on < response_due:
        response_due = before_meeting_on

    # The invariant every downstream silence fact rests on. Guarded above for
    # the meeting date; re-checked here so no future edit to the arithmetic can
    # quietly produce a deadline that precedes the request.
    if response_due < sent_on:
        raise ValueError(
            f"computed response_due {response_due.isoformat()} precedes sent_on "
            f"{sent_on.isoformat()}; a response window cannot close before it opens"
        )

    return request.model_copy(
        update={
            "state": RequestState.SENT,
            "sent_on": sent_on,
            "response_due": response_due,
        }
    )


def mark_answered(request: RecordsRequest, answered_on: date) -> RecordsRequest:
    """Record that the school produced records, ending this request's silence.

    A late answer is still an answer: an UNANSWERED_OVERDUE request may be
    answered, and doing so stops it generating further silence facts.
    ``response_due`` is preserved so how late the answer was stays computable.
    """
    if request.state not in (RequestState.SENT, RequestState.UNANSWERED_OVERDUE):
        raise ValueError(
            f"request {request.request_id} is {request.state.value}; "
            "only a sent request can be answered"
        )

    return request.model_copy(
        update={"state": RequestState.ANSWERED, "answered_on": answered_on}
    )


def refresh_states(requests: list[RecordsRequest], today: date) -> list[RecordsRequest]:
    """Flip SENT requests whose response deadline has passed to UNANSWERED_OVERDUE.

    The flip happens the day AFTER ``response_due``, not on it: 34 CFR 300.613(a)
    allows production "in no case more than 45 days after the request", so a
    school that produces records on day 45 has complied. Overdue means the
    deadline was passed, and the first day that is true is ``response_due + 1``.

    Idempotent, and every other state is left alone. Updated requests are
    returned as copies so the pre-flip objects stay intact for the audit trail.
    """
    refreshed: list[RecordsRequest] = []
    for request in requests:
        overdue = (
            request.state is RequestState.SENT
            and request.response_due is not None
            and today > request.response_due
        )
        if overdue:
            refreshed.append(
                request.model_copy(update={"state": RequestState.UNANSWERED_OVERDUE})
            )
        else:
            refreshed.append(request)
    return refreshed


def silence_events(
    requests: list[RecordsRequest],
    ledger: IEPLedger,
    today: date,
) -> list[ServiceEvent]:
    """Turn each overdue, unanswered request into dated documented-silence facts.

    One event per service the request covered, dated at ``response_due`` — the
    day the obligation to produce was breached, which is the date a letter or a
    state complaint has to plead.

    WHAT THESE EVENTS MEAN, EXACTLY: ``delivered=False`` with ``minutes=0`` and
    ``Provenance.DOCUMENTED_SILENCE`` asserts that the school produced no
    records for this service and period despite a request whose statutory
    deadline has passed. It does NOT assert that the service went undelivered —
    only the school knows that, and its refusal to say is the whole point.

    TWO OBLIGATIONS THIS PUTS ON EVERY CONSUMER, because nothing here can
    enforce them:

    1. WORDING. A citation built from one of these events must speak about the
       missing record, not about the session. "No service record was produced
       by the district for this period" is what the event supports; "session
       recorded as not delivered" is not, and is the one claim silence can
       never establish. Code that renders evidence by branching on
       ``delivered`` alone will produce the second sentence, so it must branch
       on ``provenance`` first.
    2. ARITHMETIC. These events must be counted as UNDOCUMENTED minutes, never
       as proven non-delivery, and they must not consume a promised-session
       slot in any "sessions with a record either way" tally. A silence event
       documents the absence of a record; it says nothing about the
       disposition of any particular session. Counting it as an accounted-for
       session shrinks the undocumented bucket, which would make exercising
       the parent's records right *increase* the share of the shortfall stated
       without the undocumented hedge — exactly backwards.

    THE RETURN VALUE IS A FULL RECOMPUTATION, NOT AN INCREMENT. The same
    overdue request yields the same event — same date, same service, same
    source — on every call for as long as it stays unanswered. A caller must
    REPLACE its previous silence set with this result, never append to it;
    appending multiplies one silence fact into many and, in any consumer that
    counts events against promised sessions, compounds the distortion above.
    Within a single call, events are deduplicated on
    ``(source, service, event_date)``.

    Service names are normalized to the ledger's own spelling so reconciliation
    can join on them; a service the ledger does not promise is skipped, because
    a silence fact that cannot be matched to an obligation cannot be reconciled.
    Requests whose ``response_due`` has not yet arrived are skipped too — the
    agent never asserts a silence that has not happened yet — as are requests
    whose ``response_due`` precedes their own ``sent_on``, which is a
    contradictory record that would date a breach before the request existed.
    """
    canonical: dict[str, str] = {}
    for obligation in ledger.obligations:
        canonical.setdefault(obligation.service.strip().lower(), obligation.service)

    events: list[ServiceEvent] = []
    seen: set[tuple[str, str, date]] = set()
    for request in requests:
        if request.state is not RequestState.UNANSWERED_OVERDUE:
            continue
        if request.response_due is None or request.response_due > today:
            continue
        if request.sent_on is not None and request.response_due < request.sent_on:
            continue

        for service in request.services:
            name = canonical.get(service.strip().lower())
            if name is None:
                continue
            key = (request.request_id, name, request.response_due)
            if key in seen:
                continue
            seen.add(key)
            events.append(
                ServiceEvent(
                    event_date=request.response_due,
                    service=name,
                    minutes=0,
                    delivered=False,
                    provenance=Provenance.DOCUMENTED_SILENCE,
                    source=request.request_id,
                )
            )
    return events


def _window_start(ledger: IEPLedger, covered_through: date | None) -> date | None:
    """First day not yet covered by a request, bounded by when services began."""
    starts = [o.start_date for o in ledger.obligations]
    if not starts:
        return None
    earliest = min(starts)
    if covered_through is None:
        return earliest
    return max(earliest, covered_through + timedelta(days=1))


def _services_in_window(ledger: IEPLedger, start: date, end: date) -> list[str]:
    """Ledger service names whose obligation overlaps the window, in IEP order."""
    overlapping = [
        o.service
        for o in ledger.obligations
        if o.start_date <= end and o.end_date >= start
    ]
    return list(dict.fromkeys(overlapping))


_ID_SUFFIX_RE = re.compile(r"(\d+)$")


def _next_request_id(existing: list[RecordsRequest]) -> str:
    """The next id, always numerically above every id already in use.

    Seeded from the highest numeric suffix present rather than from the count
    of requests, so a sparse or externally numbered history (``req-005`` alone)
    yields ``req-006`` and not ``req-002``. Uniqueness alone is not enough: the
    correspondence history is an audit trail, and a parent, a district clerk or
    a hearing officer sorting requests by id has to see them in the order they
    were made.
    """
    taken = {r.request_id for r in existing}
    highest = 0
    for request in existing:
        match = _ID_SUFFIX_RE.search(request.request_id)
        if match:
            highest = max(highest, int(match.group(1)))

    n = highest + 1
    while f"req-{n:03d}" in taken:
        n += 1
    return f"req-{n:03d}"
